export const ADD_TO_FAVORITE_START = 'ADD_TO_FAVORITE_START';
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS';
export const ADD_TO_FAVORITE_ERROR = 'ADD_TO_FAVORITE_ERROR';

export const REMOVE_FROM_FAVORITE_START = 'REMOVE_FROM_FAVORITE_START';
export const REMOVE_FROM_FAVORITE_SUCCESS = 'REMOVE_FROM_FAVORITE_SUCCESS';
export const REMOVE_FROM_FAVORITE_ERROR = 'REMOVE_FROM_FAVORITE_ERROR';

export const GET_FAVORITE_START = 'GET_FAVORITE_START';
export const GET_FAVORITE_SUCCESS = 'GET_FAVORITE_SUCCESS';
export const GET_FAVORITE_ERROR = 'GET_FAVORITE_ERROR';

export const GET_TRACKS_START = 'GET_TRACKS_START';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_ERROR = 'GET_TRACKS_ERROR';

export const GET_TRACK_BY_ID_START = 'GET_TRACK_BY_ID_START';
export const GET_TRACK_BY_ID_SUCCESS = 'GET_TRACK_BY_ID_SUCCESS';
export const GET_TRACK_BY_ID_ERROR = 'GET_TRACK_BY_ID_ERROR';

export const GET_SELECTION_START = 'GET_SELECTION_START';
export const GET_SELECTION_SUCCESS = 'GET_SELECTION_SUCCESS';
export const GET_SELECTION_ERROR = 'GET_SELECTION_ERROR';

export const GET_SELECTION_BY_ID_START = 'GET_SELECTION_BY_ID_START';
export const GET_SELECTION_BY_ID_SUCCESS = 'GET_SELECTION_BY_ID_SUCCESS';
export const GET_SELECTION_BY_ID_ERROR = 'GET_SELECTION_BY_ID_ERROR';

export const SET_CURRENT_TRACK_ID = 'SET_CURRENT_TRACK_ID';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_PLAYLIST_SIZE = 'SET_PLAYLIST_SIZE';